### ISSUE TITLE
D3 in charted_test.dart

### ISSUE THREAD

**Issue by rayk** [rwl/graphlib#2]
Hi Richard 

Just working through your graph lib and was wondering what d3 refers to..

```
setUp(() {
      svg = d3.select("body").append("svg");
      g = new Graph()
```

Where you calling d3.js...?

I just trying to your charted example running..

**Comment by rwl** [comment]
The tests for the layout library and the charted renderer are not passing yet.  The line you are referring to would need to be translated to something like:

https://github.com/rwl/dagre_charted/blob/charted/test/renderer_test.dart#L56
